### ISSUE TITLE
Get rid of `beberlei/assert`

### ISSUE THREAD

**Issue by schlessera** [brightnucleus/config#16]
The `beberlei/assert` package is producing all sorts of issues and needs to go.

Either look for a better replacement or code a `brightnucleus/[assert|expect|verify]` package.

Requirements:
1. No functions, only classes (static methods are okay). Functions mess with the Composer autoloader.
2. Customizable messages.
3. Customizable extensions (at least provide a way to set the exceptions' namespace, for all-around replacement).

**Comment by GaryJones** [comment]
> producing all sorts of issues

Such as?

**Comment by schlessera** [comment]
- The fluent interface is buggy and sometimes messes with Composer autoloading
- The fluent interface doesn't let you use custom exceptions (https://github.com/beberlei/assert/issues/57)
- The messages are hard to translate (https://github.com/webmozart/assert#faq)
- The package is partially abandoned (https://twitter.com/beberlei/status/743917012699709440)
