### ISSUE TITLE
Add a mechanism to retrieve values several levels deep.

### ISSUE THREAD

**Issue by schlessera** [brightnucleus/config#7]
Suppose we have the following config:

```
[
   'level1' => [
      'level2' => [
         'level3' => [
            'key' => 'value',
         ],
      ],
   ],
]
```

Add functionality to retrieve the deeply nested key in one request, like so:

```
$value = $config->get('level1', 'level2', 'level3', 'key');
```

**Comment by GaryJones** [comment]
A nicer implementation would be one of:

``` php
$value = $config->get('level1/level2/level3/key');
$value = $config->get('level1\level2\level3\key');
$value = $config->get('level1.level2.level3.key');
```

Perhaps pick one as the default, and either accept a Config class param for what the divider should be, or allow and try all cases when an individual key has one of the characters in it, before throwing an exception.

**Comment by schlessera** [comment]
Good idea for a next step.
